### ISSUE TITLE
Add form model to project

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-votanti#19]
Linked to Client issue https://github.com/code4romania/monitorizare-vot-votanti-admin/issues/14

A new entity needs to be added to the project, name of the entity is form, this entity will hold forms displayed in the app.
Fields:
titlu -> string
autor -> user reference
data -> date field
status -> string
fields -> list of fields that need to be displayed as part of the form

**Comment by mirelanemes** [comment]
work in progress

**Comment by mirelanemes** [comment]
https://github.com/code4romania/monitorizare-vot-votanti-api/pull/25

**Comment by RaduCStefanescu** [comment]
Issue is fixed by https://github.com/code4romania/monitorizare-vot-votanti-api/pull/25
