### ISSUE TITLE
Add form controller to access form entity and perform operations on form

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-votanti#20]
Linked to https://github.com/code4romania/monitorizare-vot-votanti-admin/issues/14
Linked to https://github.com/code4romania/monitorizare-vot-votanti-api/issues/19
Linked to https://github.com/code4romania/monitorizare-vot-votanti-admin/issues/15

Add form controller in order to perform operations on form entities:
- Add new form
- Display all forms
- Activate/Deactivate form
- Edit form
- Delete form

**Comment by mirelanemes** [comment]
work in progress

**Comment by mirelanemes** [comment]
needs review https://github.com/code4romania/monitorizare-vot-votanti-api/pull/25

**Comment by RaduCStefanescu** [comment]
This is fixed by https://github.com/code4romania/monitorizare-vot-votanti-api/pull/25
