### ISSUE TITLE
Restructure/build another forms endpoint

### ISSUE THREAD

**Issue by CristiHabliuc** [code4romania/monitorizare-vot-votanti#24]
I suggest we either restructure this endpoint, or create a new one that has a better data. We need this in order to have the form description along with the ID, to be displayed in the UI.

Right now, the `/formular/versiune` endpoint returns this:

```
{
    "versiune": {
        "A": 3,
        "B": 3,
        "C": 2
    }
}
```

I would suggest that the returned object be an array of objects, instead of a hashmap, so we can store more properties.

It would make sense building a different one, since its purpose would be a bit different.

```
GET /formulare

{
    "formulare": [
        {
            "id": "A",
            "descriere": "Primul formular",
            "ver": 3
        },
        {
            "id": "B",
            "descriere": "Al doilea",
            "ver": 2
        },
        ...
    ]
}
```

This way we can show the description in the UI (before today it was hard coded in the app):

```
"Label_FormA" = "Saturday Form";
"Label_FormB" = "Sunday Form";
"Label_FormC" = "Counting Form";
```

**Comment by RaduCStefanescu** [comment]
This was open by mistake in the wrong repo.
Moved it to the Mobile API here https://github.com/code4romania/monitorizare-vot/issues/113
