### ISSUE TITLE
Enhance PrecinctController with endpoint to add precincts

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-votanti#27]
Currently the precincts are created and inserted manually by running a script to import this information in the database.

The PrecinctController needs to be enhanced to receive requests for insert from the frontend.
The PrecinctController should be able to receive a csv/xlsx file, similar to the one in resources/files/precincts and update the information in the database.

**Comment by andrei1489** [comment]
I can take this

**Comment by RaduCStefanescu** [comment]
In progres @ Andrei Dumitrescu

**Comment by RaduCStefanescu** [comment]
This issue can be closed, it is fixed in #33
