### ISSUE TITLE
Edit the type of incidents available in the application

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-votanti#28]
Enhance the IncidentType controller to accept a POST method for adding incident types from the frontend.
The datamodel of the request should be the same as the datamodel persisted:
- Label
- Code
- Name
Please check IncidentTypeController.php and the api_routes.php to create the new route.

Enhance the IncidentType controller to accept a POST method for adding a list of incident types from the front end. The datamodel of the objects sent from frontend is the same as above: 
- Label
- Code
- Name
Please check IncidentTypeController.php and the api_routes.php to create the new route.

**Comment by Kentus** [comment]
In progress.

**Comment by RaduCStefanescu** [comment]
Fixed in #32
