### ISSUE TITLE
Return number of unread/accepted/rejected messages

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-votanti#40]
The backend should return the number of messages that are unread/accepted/rejected.
The information needs to be used on the Messages page on the frontend.

<img width="1504" alt="Screenshot 2019-08-13 at 18 08 37" src="https://user-images.githubusercontent.com/15039873/62954839-be138480-bdf8-11e9-8eaf-8cce01b07ab3.png">

**Comment by socialskillsforitpeople** [comment]
In progress @socialskillsforitpeople

**Comment by socialskillsforitpeople** [comment]
Closed by https://github.com/code4romania/monitorizare-vot-votanti-api/pull/42.
